### ISSUE TITLE
flick-demo firmare version formatting

### ISSUE THREAD

**Issue by francesco-vannini** [PiSupply/Flick#12]
The line for the firmware version is a bit messy and fairly long. It could with a bit of tiding up.

**Comment by ukscone** [comment]
still ugly but a bit better. i've done a PR
https://github.com/PiSupply/Flick/pull/13

**Comment by shawaj** [comment]
Merged it - do you want to clear it up further @francesco-vannini or are you happy with that now?

**Comment by francesco-vannini** [comment]
Happy with it, thanks both.
