### ISSUE TITLE
Communication seems good, but no Gesture Data

### ISSUE THREAD

**Issue by tomvdb** [PiSupply/Flick#14]
I've installed the flick hat zero and did the one line install. It seems to be talking to the chip (ie. it shows the versions, etc), but I'm not getting any gesture data when running flick-demo. Am I missing something ?

![image](https://user-images.githubusercontent.com/1420347/27261356-a7da6d32-5441-11e7-93bd-0ca65c3ac72f.png)

**Comment by francesco-vannini** [comment]
Hi @tomvdb , indeed that's rather strange. can I get an output of
i2cdetect -y 1
Also do you have another Pi you can test with? I presume you are using a Zero :) do you have a Bx you can test with? Could you also try a fresh, updated Raspbian?

**Comment by tomvdb** [comment]
ok, so I tried with a fresh install, updated the packages and installed the flick software. Still no go, same result.

i2cdetect -y 1 gives the following:

![image](https://user-images.githubusercontent.com/1420347/27300872-7c9c62f6-5531-11e7-9fc3-80922c50e85f.png)

I also tried this in a pi3, same result :(

**Comment by shawaj** [comment]
Did you try on the pi 3 with a fresh SD card and fresh version of NOOBS, not the same one as used for pi zero?

Also does it still not work if you use it on the machine itself rather than with putty?

**Comment by tomvdb** [comment]
(1) first I flashed the sd in the zero again with a new fresh version of raspbian, did the updates and installed the software. same result
(2) then I took a different sd, flashed a new raspbian on there, did the updates and tried it on the pi3, same result.

I didn't ssh into the pi3, that was straight on the monitor/keyboard setup.

I also tried both the lite and the full raspbian :(

**Comment by francesco-vannini** [comment]
I think at this point we might need to look into replacing the board. Did
you buy it from us? If so can you open a support request on
https://www.pi-supply.com/contact-us/

**Comment by tomvdb** [comment]
No, I bought it locally in South Africa at the pishop.co.za 

I will open a support ticket with them. Thanks for the help.

**Comment by shawaj** [comment]
Guessing the screenshot were taken through SSH as they look like putty?

But in any case good you've tried it direct from Pi 3 terminal.

@francesco-vannini do you think it's worth attempting to re flash the firmware just as a last ditch attempt to fix the board? 

It seems like it must be programmed as firmware data is showing and it would be tested out of the factory but it seems strange it can find the chip but not detect any gestures. Not seen this before!

**Comment by shawaj** [comment]
Also @tomvdb do you get any signs of life at all if you hold your hand completely over the device, as close as you can?

Anything in the X, Y, Z field at all?

**Comment by tomvdb** [comment]
Thats correct, screenshots were made while using putty ssh'd into the pi zero. I get the same on the terminal though on the pi3, I can take some photos if needed.

no, no signs at all. no matter where I put my hand all the way up to touching it.

I'm willing to try and reflash the firmware? how would I go about doing that?

**Comment by francesco-vannini** [comment]
@tomvdb refer to the firmware page https://github.com/PiSupply/Flick/tree/master/hardware/Firmware/update and get the HAT enz file

From within /home/pi/Flick/hardware/Firmware/update
cp ../Flick_Zero_V1.1.enz .
./flickupdate

**Comment by tomvdb** [comment]
hey, the firmware update seemed to have done the trick. Its working now on my pi3 :)

![image](https://user-images.githubusercontent.com/1420347/27348038-04e96818-55f3-11e7-9cba-4d35a4acf9cb.png)

**Comment by shawaj** [comment]
Awesome!

**Comment by shawaj** [comment]
Glad that worked for you

**Comment by gazhay** [comment]
I've got exactly the same problem. I've got as far as trying to flash the firmware and get

````
    /Flick/firmware/update $ ./flickupdate 
    can't open  gpio xfer direction file
    can't open  pin file
    can't open  gpio xfer direction file
    can't open  gpio xfer direction file
    can't open  pin file
     Loader record_count 109
     lib record_count 222
    Flashing loader.
    gestic_flash_begin 
````
Its been stuck at that for 20 mins

**Comment by gazhay** [comment]
Ok, have tried it as sudo, and it seemed to make it flash, after a reboot, still nothing. 

````
    ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
       │ Firmware valid: Yes                                                                                        │
       │ Hardware Revison: 99.128                                                                                   │
       │ Params Start Addr: 0x7300                                                                                  │
       │ Library Loader Version: 19.100                                                                             │
       │ Library Loader Platform: Hillstar                                                                          │
       │ Firmware Start Addr: 0x1000                                                                                │
       │ Firmware Version: 1.3.14;p:HillstarV01;x:                                                                  │
       │ DSP: ID9000r2963;i:B;f:22500;nMsg;s:Rel_1_3_prer1784:NM;                                                   │
       └────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
    
````

**Comment by shawaj** [comment]
To anyone seeing this thread after it has been closed.......

The firmware issue is very unlikely. You should not reflash the firmware unless it is recommended by one of us directly to you as you can break the board by doing so. It should only be done after all other tests have been performed and ONLY if one of us requests it.

**Comment by shawaj** [comment]
@mike-shock can you please start a new issue with exactly what you're seeing?

**Comment by lionelvrolijk** [comment]
guys i need help with mine i accidently run the wrong firmware update
