### ISSUE TITLE
Reopen Issue #14

### ISSUE THREAD

**Issue by gazhay** [PiSupply/Flick#16]
Just in case it gets missed, I'm still having the same issue as #14 

Tried flashing firmware to no end.

**Comment by francesco-vannini** [comment]
what does
sudo i2cdetect -y 1
report?

**Comment by gazhay** [comment]
The same as the post by tomvdb on issue #14 .

    42

**Comment by gazhay** [comment]
Should say I was on a fresh NOOBS Raspbian install on an rpi3

**Comment by shawaj** [comment]
@gazhay can you tell us what Flick board you are using and what Pi?

Have you tried starting from scratch again? The firmware issue is very unlikely. You should not reflash the firmware unless it is recommended by one of us directly to you as you can break the board by doing so. It should only be done after all other tests have been performed.

**Comment by gazhay** [comment]
Flick large and an rpi3.
I have an pi 2, zero and zero w if it would make a difference?

I started from scratch, but can try again with a fresh sd. Won't be able to for a few days but will report back when I do.

**Comment by francesco-vannini** [comment]
I am sure you did but have you connected the board as shown here?
https://www.pi-supply.com/make/flick-quick-start-faq/#flick-large-board

**Comment by gazhay** [comment]
Yes, I have wired up as in that diagram. 
FYI, I can control the LEDs via gpio.

**Comment by gazhay** [comment]
Still nothing on a brand new card with a new noobs and fully apt updated.

**Comment by francesco-vannini** [comment]
OK @gazhay at this point I think you might want to get a replacement. Did you buy directly from us? If so can you get in touch via https://www.pi-supply.com/contact-us/

**Comment by gazhay** [comment]
Sadly, I bought it from pi-hut. I'll contact them directly.

**Comment by francesco-vannini** [comment]
Please do let us know how this goes.

**Comment by francesco-vannini** [comment]
Hi @gazhay did you get a replacement? Are things working ok now?

**Comment by francesco-vannini** [comment]
Closing this as no answer provided for 16 days. By all means @gazhay do get in touch if you need to reopen it.

**Comment by gazhay** [comment]
Never got a replacement and vendor now out of stock. If I ever manage to get another one will post a new issue.

**Comment by shawaj** [comment]
Have you tried flashing the firmware onto the chip again? That may fix it

**Comment by gazhay** [comment]
I did before I sent it back, no change. And then I was rebuked for flashing firmware at all.

**Comment by shawaj** [comment]
Pi hut will likely reorder from us pretty soon :-)

Have they got the faulty one back?

**Comment by gazhay** [comment]
They do.

**Comment by shawaj** [comment]
Ok we'll get in touch with them right now
