### ISSUE TITLE
Upload Logo

### ISSUE THREAD

**Issue by francesco-vannini** [PiSupply/Flick#22]
![flick](https://user-images.githubusercontent.com/16068311/30543656-d483676c-9c7b-11e7-8d7e-b05572902177.png)

**Comment by francesco-vannini** [comment]
![flick](https://user-images.githubusercontent.com/16068311/30544599-f0c3570e-9c7e-11e7-9f3f-74282a271749.png)

**Comment by francesco-vannini** [comment]
Use this thread to add pictures

**Comment by ChristopherRush** [comment]
![flick-github-banner](https://user-images.githubusercontent.com/1878314/73880628-afad9f00-4856-11ea-975a-ec95b6ffacbe.png)
