### ISSUE TITLE
c++ flick_example does not work

### ISSUE THREAD

**Issue by tvoverbeek** [PiSupply/Flick#34]
There is one statement missing in flick_example.cpp:
```
        usleep(250000);
        int ret = flick.SetRuntimeParameter(0xa1, 0x1f, 0xFFFFFFFF); // lock data output   <-----
        ret = flick.SetRuntimeParameter(0x80, 0x1b, 0x1F); // disable calibration
        //printf("ret: %d \n", ret);
```
Enabling the output makes it work.

**Comment by shawaj** [comment]
Thanks @tvoverbeek - is that the only issue with it? 

Which line is this on so can easily find it to fix?

**Comment by tvoverbeek** [comment]
Yes, rest is OK.
The extra line has to be added after line 117 in flick_example.cpp

**Comment by shawaj** [comment]
Fixed now - https://github.com/PiSupply/Flick/blob/master/firmware/libcpp/flick_example.cpp

Does that look ok @tvoverbeek ?

Guess we need to upload a new compiled version as well, once you are happy with it

**Comment by tvoverbeek** [comment]
OK

**Comment by shawaj** [comment]
Have you got a compiled version you could upload? If not no worries, I'll sort it when I'm next by a Pi

**Comment by tvoverbeek** [comment]
Compiled version uploaded

**Comment by shawaj** [comment]
Thanks :-)
