### ISSUE TITLE
gpio mode 17 out; gpio write 17 0; gpio write 17 1; i2cdetect -y 1

### ISSUE THREAD

**Issue by ryanteck** [PiSupply/Flick#58]
This will likely fail, it's not pin 17. Need to change.

**Comment by tvoverbeek** [comment]
Where in the code is this????
BCM numbering GPIO 17 is pin 11 on the 40 pin connector (= Flick SW_RESET)

**Comment by ryanteck** [comment]
We have it on the Readme.md to reset the pin when using Wiringpi, I just need to update the Readme but I'm not on my computer which has all my stuff setup on.

I'll just do it the other way.

**Comment by tvoverbeek** [comment]
OK. Saw you fixed it already.
