### ISSUE TITLE
AttributeError: 'AsyncWorker' object has no attribute 'isAlive' in flicklib.py

### ISSUE THREAD

**Issue by danny-atten** [PiSupply/Flick#66]
Hi,

I'm installing the Flick code on a new build of Raspbian with Python 3.9.2. When trying to run "flick-demo", I'm getting an error saying that AttributeError: 'AsyncWorker' object has no attribute 'isAlive'.

I searched around and found another Github issue from Jan. 1, 2021 with a similar issue. See the link [here](https://github.com/jupyter-vim/jupyter-vim/issues/51). It looks like the method isAlive() was renamed to is_alive() in Python 3.9. Would it be possible to update this in lines 103 and 108 of flicklib.py?

I have also attached the full error message here. 

[flick error message.txt](https://github.com/PiSupply/Flick/files/8037672/flick.error.message.txt)

Thanks!

**Comment by tvoverbeek** [comment]
Done.
Thanks for catching this.
